Repository Eijebong/Archipelago-index, pull requests merged in 2025-06, with the labels that each got.

#552 Update fe8
  index/fe8.toml
Labels: blocked by apworld

#589 Update Sonic Heroes
  index/sonic_heroes.toml
Labels: blocked by apworld

#629 Update powerwashsimulator
  index/powerwashsimulator.toml
Labels: blocked by apworld, R-Fuzz

#637 Update th06
  index/th06.toml
Labels: blocked by apworld, R-Fuzz

#638 Add th07
  index/th07.toml
Labels: blocked by apworld, R-Fuzz

#367 Add Luigi's Mansion 0.4.9
  index/luigismansion.toml
Labels: blocked by apworld, R-Fuzz

#568 Update tloz_oos
  apworlds/tloz_oos-7.2.2+ishigh-2.apworld
  index/tloz_oos.toml
Labels: blocked by apworld, R-Tests

#675 Update double dash
  index/mario_kart_double_dash.toml
Labels: blocked by apworld, R-Fuzz
